service: doctors-appointment-backend

frameworkVersion: ">=3.0.0"

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ap-south-1
  memorySize: 512
  timeout: 15
  lambdaHashingVersion: 20201221
  environment:
    NODE_ENV: production
    STAGE: ${self:provider.stage}
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRES_IN: ${env:JWT_EXPIRES_IN, '1d'}
    CORS_ORIGIN: ${env:CORS_ORIGIN, '*'}

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 3
  dotenv:
    path: .env
  serverless-offline:
    httpPort: 3000

package:
  individually: true
  patterns:
    - '!**/*'
    - 'dist/**'
    - 'node_modules/**'
    - 'prisma/**'
    - 'package.json'
    - 'package-lock.json'
    - 'serverless.yml'

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
          method: ANY
          path: /{proxy+}
      - httpApi:
          method: ANY
          path: /
